# Generated by Django 2.0.3 on 2018-09-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20180927_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brief_introduction',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
