# Generated by Django 2.0.3 on 2018-10-24 01:41

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20181020_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='users-pictures'),
        ),
    ]
