# Generated by Django 2.0.3 on 2018-10-24 01:41

from django.db import migrations


def migrate_avatar_to_pictures(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model('authentication', 'User')

    for user in User.objects.filter(avatar__isnull=False):
        user.picture = user.avatar
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_picture'),
    ]

    operations = [
        migrations.RunPython(migrate_avatar_to_pictures)
    ]
