# Generated by Django 2.0.3 on 2018-10-24 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_migrate_avatar_to_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
