FROM python:3.6.4-alpine3.7

RUN apk update && apk add openrc postgresql-dev jpeg-dev zlib-dev gcc musl-dev libxml2-dev libxslt-dev nfs-utils
RUN rc-update add nfsmount default

RUN mkdir /base

ADD . /base

RUN pip install -r /base/requirements/prod.txt

WORKDIR /base/join

EXPOSE 8000

CMD ["daphne", "join.asgi:application", "--bind", "0.0.0.0", "--port", "8000", "--verbosity", "1"]
