# Generated by Django 2.0.3 on 2018-10-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='format',
            field=models.CharField(default='PNG', max_length=30),
        ),
        migrations.AddField(
            model_name='slide',
            name='quality',
            field=models.CharField(default='15', max_length=30),
        ),
        migrations.AddField(
            model_name='slide',
            name='resize_to',
            field=models.CharField(default='1920x1080', max_length=30),
        ),
    ]
