# Generated by Django 2.0.3 on 2018-10-27 21:17

from django.db import migrations, models
import django_extensions.db.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTitleSlug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('file', sorl.thumbnail.fields.ImageField(upload_to='images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
