# Generated by Django 2.0.3 on 2018-10-20 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_auto_20181002_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='followed_by',
            field=models.ManyToManyField(related_name='projects_followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='liked_by',
            field=models.ManyToManyField(related_name='projects_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='viewed_by',
            field=models.ManyToManyField(related_name='projects_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
