# Generated by Django 2.0.3 on 2018-10-23 23:40

from django.db import migrations


def migrate_photos_to_images(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Project = apps.get_model('project', 'Project')
    ProjectImage = apps.get_model('project', 'ProjectImage')

    for project in Project.objects.filter(gallery__isnull=False):
        photos = project.gallery.photos.all()
        for photo in photos:
            ProjectImage.objects.create(project=project, file=photo.image)


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projectimage'),
    ]

    operations = [
        migrations.RunPython(migrate_photos_to_images)
    ]
