# Generated by Django 2.0.3 on 2018-10-24 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_projectcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gallery',
        ),
    ]
