# Generated by Django 2.0.3 on 2018-10-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='tag',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
